version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      gradle-non-major:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: npm
    directory: /frontend/compliance-portal
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      frontend-non-major:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /infra/docker
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      docker-non-major:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - "*"
